### ISSUE TITLE
[bug]: Error on "Overview" tiles after upgrade

### ISSUE THREAD

**Issue by thiloms** [ioBroker/ioBroker.admin#2708]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

After upgrading the Admin-Adapter to v7.1.5 the tiles and links on the "Overview" page has been different.
- The _Admin_ tile is not shown anymore
- The _Node-RED_ tile is shown twice
- The _Node-RED_ (both) tiles and the _REST API_ tile (both Adapters are running on the same instance) are pointing to a "unknown" URL **%web_bind%:1880** (for Node-RED) and **%web_bind%:8093** (for REST API).
- Node-RED and REST API are running and I can open the links via the Instances page by clicking on the "instance link" icon.
- The zigbee2mqtt, which is running on a separate Docker container, showing the correct URL (IP of that instance) and I'm able to click on the tile to open it in a separate browser tab.

![image](https://github.com/user-attachments/assets/ede9cc11-008f-4be0-bec0-94ef6aa9d662)

If I revert the Admin adapter back to v6.17.6 (currently latest v6), the tiles are shown correctly again (including the Admin tile):

![image](https://github.com/user-attachments/assets/b1884435-be9d-4111-b7e7-2d6a2624ad38)

As I also updated the Node-RED and REST API adapter yesterday, my first thought was an error with those adapters and I also found two similar issues at the Node-RED adapter:

Wrong URL: https://github.com/ioBroker/ioBroker.node-red/issues/507
Duplicate Node-Red tiles: https://github.com/ioBroker/ioBroker.node-red/issues/498

But as soon I revert back the admin adapter all this issues seems to be solved again. So I guess the issues above at Node-RED are not a problem of the Node-RED adapter they are only related to the Admin adapter.

btw: I run ioBroker within a Container of the official Docker image (:latest-v10) using macvlan network.

### To Reproduce

See screenshots above to reproduce
1. Use existing ioBroker with "old" (v6) Admin adapter and Node-RED + REST API adapter
2. Look at Overview page (OK)
3. Upgrade Admin adapter to latest (v7.1.5)
4. Look at Overview page (problem as described above)
5. Revert Admin adapter back to v6.17.6
6. Look at Overview page (everything OK again)

### Expected behavior

On overview page:
- The Admin tile should be visible after upgrade
- No duplicate tiles for Node-RED
- URLs of tiles pointing to correct locations 

### Screenshots & Logfiles

see above in description.

### Adapter version

v7.1.5

### js-controller version

v6.0.11

### Node version

v20.17.0

### Operating system

official Docker image (Debian GNU/Linux 12 (bookworm))

**Comment by GermanBluefox** [comment]
Must be fixed with 7.2.0

**Comment by Feuer-sturm** [comment]
@thiloms  please check with current beta version (>= 7.2.6)

**Comment by thiloms** [comment]
@Feuer-sturm , @GermanBluefox 
Today I installed the current Admin Adapter v7.2.6.

Sorry to say, that only parts of the problem are fixed.

1. Fixed: The links seems to be correct now and from the overview I can click on them and then a new tab will show the Adapter Link like _Node-RED_ and _REST API_ (_zigbee2mqtt_ as an external address works before with Admin Adapter v7.1.5)
2. Not Fixed: The _Node-RED_ tile is shown twice
I still see duplicated Note-Red entries now but at least I can click on the URL (See 1.)
3. Not fixed: The _Admin_ tile is not shown anymore
I don't require the _Admin_ tile at the overview page as the overview page is shown by the _Admin_ adapter anyway. So maybe this is not a real bug but it differs from version 6.

Screenshot:
![ioBroker Admin v7 2 6](https://github.com/user-attachments/assets/67676d30-b6d2-4916-bca3-fabd6cef1107)

**Comment by GermanBluefox** [comment]
> 3\. Not fixed: The _Admin_ tile is not shown anymore

Admin itself is extra filtered out. As it is no use for it. 
So only double node-red stays as error
